# Generated by Django 3.1 on 2022-06-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220618_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product_gallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
